# Generated by Django 3.1.7 on 2021-02-27 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(default='')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(default='')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('vegetarian_food', models.BooleanField(blank=True, default=False, verbose_name='vege?')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
